# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '9.0'
target 'AppsMobileCompany' do
	project 'AppsMobileCompany.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
  pod 'Firebase/Auth'
  pod 'PhoneVerificationController'
end
